# -*- coding: utf-8 -*-
"""automate_Tabina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prp53XrEyVRGrLHwZ7OCHB8R8oU0OCs1
"""

import pandas as pd

# 1. Load raw dataset
df = pd.read_csv("heart_disease_uci.csv")

# 2. Binary target
df["num"] = (df["num"] > 0).astype(int)

# 3. Drop kolom yang tidak dipakai
df = df.drop(columns=["id", "dataset"], errors="ignore")

# 4. Handle missing values
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# 5. Encoding
df_clean = pd.get_dummies(df, columns=cat_cols, drop_first=True)

# 6. Save clean dataset
df_clean.to_csv("heart_disease_clean.csv", index=False)

print("✅ Preprocessing selesai. Dataset bersih tersimpan.")